# Generated by Django 5.1 on 2024-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('sales_type', models.CharField(blank=True, default='Product Sales', max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('payment_receive', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=100)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Banking', 'Mobile Banking')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
