# Generated by Django 5.1 on 2024-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.CharField(blank=True, max_length=500, null=True)),
                ('model', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Pack', 'Pack'), ('Pcs', 'Pcs'), ('KG', 'KG'), ('Ltr', 'Ltr')], max_length=100)),
                ('in_stock', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='prducts/')),
            ],
            options={
                'verbose_name_plural': 'All Product',
            },
        ),
    ]
