# Generated by Django 5.1 on 2024-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('department', models.CharField(choices=[('Accounts', 'Accounts'), ('HR', 'HR'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('IT and Admin', 'IT and Admin'), ('Business Development', 'Business Development')], max_length=250)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('img', models.ImageField(upload_to='employees/')),
            ],
        ),
    ]
