# Generated by Django 5.1 on 2024-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('expense_type', models.CharField(choices=[('Salary', 'Salary'), ('Utility Bills', 'Utility Bills'), ('Office Expense', 'Office Expense'), ('Others', 'Others')], default='Office Expense', max_length=200)),
                ('paid_to', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Banking', 'Mobile Banking')], default='Cash', max_length=100)),
            ],
        ),
    ]
